baseURL = "https://journal.shefreynolds.com/"
languageCode = "en-us"
title = "Shef Reynolds"

[params]
  description = "A journal by Shef Reynolds"
  author = "Shef Reynolds"

disableKinds = ["taxonomy", "term"]

[permalinks]
  posts = "/:year/:month/:slug/"
