baseURL = "https://journal.shefreynolds.com/"
languageCode = "en-us"
title = "Shef Reynolds"
theme = ""

[params]
  description = "A journal by Shef Reynolds"
  author = "Shef Reynolds"

[permalinks]
  posts = "/:year/:month/:slug/"
